# Generated by Django 3.2.3 on 2021-06-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210622_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_male',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_obese',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_pregnant',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_smoker',
            field=models.BooleanField(null=True),
        ),
    ]
