# Generated by Django 3.2.3 on 2021-06-22 02:37

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewModel',
            fields=[
                ('interview_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Interviwe ID')),
                ('creation_date', models.DateField(default=django.utils.timezone.now, verbose_name='creation date')),
                ('questions', models.JSONField()),
                ('results', models.JSONField()),
            ],
            options={
                'verbose_name': 'Interview',
                'verbose_name_plural': 'Interviews',
            },
        ),
    ]
