# Generated by Django 3.2.3 on 2021-06-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210622_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewmodel',
            name='questions',
            field=models.JSONField(default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='interviewmodel',
            name='results',
            field=models.JSONField(default='{}', null=True),
        ),
    ]
