# Generated by Django 3.2.4 on 2021-06-23 07:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210622_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewmodel',
            name='interview_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Interview ID'),
        ),
    ]
