# Generated by Django 3.2.4 on 2021-06-26 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210626_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='interview',
        ),
        migrations.AddField(
            model_name='interviewmodel',
            name='chat_history',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.chathistory', verbose_name='Chat History'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewmodel',
            name='meta',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.interviewmetadatamodel', verbose_name='Interview Metadata'),
            preserve_default=False,
        ),
    ]
