# Generated by Django 3.2.4 on 2021-06-26 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20210626_1054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paterns',
            new_name='Patern',
        ),
        migrations.RenameModel(
            old_name='Symptoms',
            new_name='Symptom',
        ),
        migrations.AlterField(
            model_name='interviewmodel',
            name='chat_history',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='base.chathistory', verbose_name='Chat History'),
        ),
    ]
