# Generated by Django 3.2.4 on 2021-06-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20210626_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desease',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Desease name'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Symptom name'),
        ),
    ]
