# Generated by Django 3.2.4 on 2021-06-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20210626_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desease',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='desease',
            name='has_hypertension',
            field=models.BooleanField(null=True, verbose_name='Hypertension'),
        ),
        migrations.AlterField(
            model_name='desease',
            name='is_injured',
            field=models.BooleanField(null=True, verbose_name='Injured'),
        ),
        migrations.AlterField(
            model_name='desease',
            name='is_obese',
            field=models.BooleanField(null=True, verbose_name='Obese'),
        ),
        migrations.AlterField(
            model_name='desease',
            name='is_pregnant',
            field=models.BooleanField(null=True, verbose_name='Pregnant'),
        ),
        migrations.AlterField(
            model_name='desease',
            name='is_smoker',
            field=models.BooleanField(null=True, verbose_name='Smoker'),
        ),
        migrations.AlterField(
            model_name='desease',
            name='max_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='desease',
            name='min_age',
            field=models.IntegerField(null=True),
        ),
    ]
