# Generated by Django 3.2.4 on 2021-06-27 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20210626_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Disease name')),
                ('min_age', models.IntegerField(blank=True, null=True)),
                ('max_age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender')),
                ('is_smoker', models.BooleanField(null=True, verbose_name='Smoker')),
                ('is_pregnant', models.BooleanField(null=True, verbose_name='Pregnant')),
                ('is_obese', models.BooleanField(null=True, verbose_name='Obese')),
                ('is_injured', models.BooleanField(null=True, verbose_name='Injured')),
                ('has_hypertension', models.BooleanField(null=True, verbose_name='Hypertension')),
                ('symptoms', models.ManyToManyField(to='base.Symptom', verbose_name='Symptoms')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=200, verbose_name='Response patern')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.symptom', verbose_name='Symptom')),
            ],
        ),
        migrations.DeleteModel(
            name='Desease',
        ),
    ]
