# Generated by Django 3.2.4 on 2021-06-27 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20210627_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='cure_method',
            field=models.TextField(blank=True, null=True, verbose_name='Steps to cure the disease'),
        ),
        migrations.AddField(
            model_name='disease',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='About the Disease'),
        ),
        migrations.AlterField(
            model_name='patern',
            name='symptom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paterns', to='base.symptom', verbose_name='Symptom'),
        ),
        migrations.AlterField(
            model_name='response',
            name='symptom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='base.symptom', verbose_name='Symptom'),
        ),
    ]
