# Generated by Django 3.2.4 on 2021-06-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_interviewmodel_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewmetadatamodel',
            name='age',
            field=models.IntegerField(null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='interviewmetadatamodel',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='interviewmetadatamodel',
            name='has_hypertension',
            field=models.BooleanField(null=True, verbose_name='Hypertension'),
        ),
        migrations.AlterField(
            model_name='interviewmetadatamodel',
            name='is_injured',
            field=models.BooleanField(null=True, verbose_name='Injured'),
        ),
        migrations.AlterField(
            model_name='interviewmetadatamodel',
            name='is_obese',
            field=models.BooleanField(null=True, verbose_name='Obese'),
        ),
        migrations.AlterField(
            model_name='interviewmetadatamodel',
            name='is_pregnant',
            field=models.BooleanField(null=True, verbose_name='Pregnant'),
        ),
        migrations.AlterField(
            model_name='interviewmetadatamodel',
            name='is_smoker',
            field=models.BooleanField(null=True, verbose_name='Smoker'),
        ),
    ]
